app_category = {
    'map': '地图导航',
    'ride-hailing': '网络约车',
    'im': '即时通讯',
    'blog': '博客论坛',
    'pay': '网络支付',
    'news': '新闻资讯',
    'shopping': '网上购物',
    'video': '短视频',
    'express': '快递配送',
    'catering': '餐饮外卖',
    'ticket': '交通票务',
    'date': '婚恋相亲',
    'jobs': '求职招聘',
    'financial': '金融借贷',
    'house': '房屋租售',
    'used-car': '二手车交易',
    'exercise': '运动健身',
    'registration': '问诊挂号',
    'browser': '浏览器',
    'input': '输入法',
    'safe': '安全管理',
}

min_permissions = {
    '地图导航': {'ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION', 'ACCESS_BACKGROUND_LOCATION', 'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '网络约车': {'ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION', 'ACCESS_BACKGROUND_LOCATION', 'CALL_PHONE'},
    '即时通讯': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '博客论坛': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '网络支付': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '新闻资讯': {},
    '网上购物': {},
    '短视频': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '快递配送': {},
    '餐饮外卖': {'ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION', 'ACCESS_BACKGROUND_LOCATION', 'CALL_PHONE'},
    '交通票务': {},
    '婚恋相亲': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '求职招聘': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '金融借贷': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '房屋租售': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '二手车交易': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '运动健身': {'ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION', 'ACCESS_BACKGROUND_LOCATION', 'SENSOR'},
    '问诊挂号': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE'},
    '浏览器': {},
    '输入法': {},
    '安全管理': {'WRITE_EXTERNAL_STORAGE', 'READ_EXTERNAL_STORAGE', 'GET_ACCOUNT', 'READ_PHONE_STATE', 'SEND_SMS', 'RECEIVE_SMS', 'READ_SMS', 'WRITE_SMS'},
}

Huawei = {
    '影音娱乐' : {'K歌', '直播', '音乐', '电视', '电台', '视频'},
    '实用工具' : {'安全性能', '工具', '输入法', '闹钟', 'Wi-Fi', '浏览器'},
    '金融理财' : {'理财', '记账', '股票基金', '彩票', '贷款', '银行'},
    '社交通讯' : {'通讯', '聊天', '婚恋', '社区'},
    '便捷生活' : {'家政', '天气日历', '家居装修', '本地生活', '电影票', '租房买房'},
    '出行导航' : {'用车', '导航', '公交地铁', '交通票务', '地图'},
    '主题个性' : {'铃声', '桌面', '锁屏', '壁纸'},
    '教育' : {'学习', '备考', '英文', '翻译'},
    '运动健康' : {'养生', '医疗', '运动', '健康'},
    '拍摄美化' : {'相册图库', '图像美化', '拍照', '影音编辑', '短视频'},
    '新闻阅读' : {'新闻', '分类信息', '体育', '杂志', '动漫', '电子书', '幽默', '有声读物'},
    '购物比价' : {'优惠', '导购', '团购', '海淘', '商城', '快递'},
    '美食' : {'餐饮', '菜谱', '生鲜', '外卖'},
    '汽车' : {'驾考', '违章查询', '汽车资讯', '养车'},
    '旅游住宿' : {'住宿', '行程助手', '旅游'},
    '商务' : {'招聘', '笔记', '办公软件', '邮箱', '效率'},
    '儿童' : {'儿歌', '母婴', '儿童教育'}
}


Xiaomi = {
    'VR' : {'游戏 - 动作', '游戏 - 冒险', '游戏 - 射击', '游戏 - 角色', '游戏 - 策略', '游戏 - 模拟', '游戏 - 休闲', '游戏 - 体育', '游戏 - 棋牌', '游戏 - 体验', '应用 - 视频', '应用 - 直播', '应用 - 音乐'},
    '实用工具' : {'系统', '浏览器', '输入法', '安全', '工具'},
    '影音视听' : {'视频', '直播', '播放器', '音乐', '电台'},
    '聊天设计' : {'聊天', '婚恋', '通讯', '交友', '社区'},
    '图书阅读' : {'听书', '漫画', '电子书', '小说', '杂志'},
    '学习教育' : {'外语', '词典', '驾考', '考试', '教育', '育儿'},
    '效率办公' : {'办公', '邮箱', '笔记', '云盘', '日程'},
    '时尚购物' : {'电商', '团购', '海淘', '导购', '时尚'},
    '居家生活' : {'闹钟', '查违章', '天气日历', '美食', '电影票', '房产居家'},
    '旅行交通' : {'用车', '地图', '旅游', '酒店', '票务', '公交地铁'},
    '摄影摄像' : {'美图', '相机', '图片分享', '相册', '视频'},
    '医疗健康' : {'减肥', '经期', '养生', '孕育', '美容', '医疗'},
    '体育运动' : {'健身', '计步', '球类', '直播'},
    '新闻资讯' : {'新闻', '资讯', '科技', '热点', '头条'},
    '娱乐消遣' : {'搞怪', '小游戏', '星座运势', '笑话'},
    '金融理财' : {'银行', '股票', '基金', '彩票', '记账', '支付', '贷款'}
}